#DOMAIN ist durch die eigene zu ersetzen.
#APP ist durch die gewünschte Subdomain zu ersetzten und im Service abzubilden.
#IP-Adresse ist durch das gewünschte Ziel zu ersetzen.

http:
 #region routers 
  routers:
    login:
      entryPoints:
        - "https"
      rule: "Host(`login.DOMAIN.de`)"
      middlewares:
        - default-headers
        - https-redirect
        - rate-limit
      tls:
        options: tls-options
      service: login 
    login_redirect:
      entryPoints:
        - "https"
      rule: "Host(`login.DOMAIN.de`) && Path(`/`, `/auth`)"
      middlewares:
        - default-headers
        - https-redirect
        - redirect-login
        - rate-limit
      tls:
        options: tls-options
      service: login
    APP:
      entryPoints:
        - "https"
      rule: "Host(`APP.DOMAIN.de`)"
      middlewares:
        - default-headers
        - https-redirect
        - rate-limit
        - keycloak
      tls:
        options: tls-options
      service: APP
  services:
    login:
      loadBalancer:
        servers:
          - url: "https://IP-ADRESSE_Keycloak:8643"
        passHostHeader: true
  middlewares:
    redirect-login:
      redirectRegex:
        regex: ".*"
        replacement: "https://login.DOMAIN.de/auth/realms/master/account/#/personal-info"
        permanent: true
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true    
    keycloak:
      forwardAuth:
        address: "http://IP-ADRESSE_ForwardAUTH:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
          - "X-Forwarded-Proto"
          - "X-Forwarded-Uri"
          - "X-Forwarded-For"
          - "X-Forwarded-Method"
          - "X-Secret"
    rate-limit:
      ratelimit:
        average: 200
        burst: 100
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
tls:
  options:
    tls-options:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
